### ISSUE TITLE
still differences in lines() between slice and rope

### ISSUE THREAD

**Issue by craigschmidt** [cessen/ropey#16]
Thanks for fixing my previous issue.  I'm not sure it exactly correct, however.  Now it is different if the document ends with \n.  In this case, the rope correctly has an empty last line, but the slice of that rope does not.  This is using ropey 0.9.1.

```rust
extern crate ropey;

use ropey::Rope;

fn main() {

    let text = "Hello there!\nHow goes it?\n";
    let rope = Rope::from_str(text);

    // should be the same as rope
    let slice = rope.slice(..);

    // but now the slice is missing the empty last line that the rope has
    assert!(slice.lines().count() == rope.lines().count());
}
```

**Comment by cessen** [comment]
Ack!  Could have sworn I put in a test-case for that.  Somehow missed it.  I've added a (properly failing) unit test and am working on a fix now.

Sorry for my sloppy initial fix!

**Comment by cessen** [comment]
@craigschmidt 
Okay, pushed a new fix to master with even more unit tests.  Turns out I did implement the fix correctly as far as the code in the iterator goes, but one of the helper functions I implemented for the fix had a really stupid bug--because I didn't write tests for it.  \*sigh\*

If you get a chance, could you test with your code?  Once you've verified, I'll do another patch release.

Thanks so much for helping out on this!

**Comment by craigschmidt** [comment]
Yes, things seem to be working now in my code.  Thanks for getting things fixed so quickly, and thanks for both ropey and led.  I've been using led as a good example of using ropey, to mess around with making a text editor.  I'm learning rust, and it is a fun project.

**Comment by cessen** [comment]
Awesome, I'll get a new patch release out now. :-)

Also, glad to hear you're finding Ropey and Led useful!  The Led codebase is pretty crufty (it was one of my first Rust projects, and though I've updated it from time to time, I've never really gone back to properly clean it up).  Led's master branch is currently in the middle of a progressive refactor, too.  Hope it's not too confusing!
