### ISSUE TITLE
Take a look at IntelliJ's immutable text

### ISSUE THREAD

**Issue by matklad** [cessen/ropey#23]
Hi!

Today I've looked at how IntelliJ handles text document, and was really surprised by how minimal and simple the core data structure is at just 500 lines of Java. I thought that you might be interested in taking a look as well:

https://github.com/JetBrains/intellij-community/blob/f41f89500540c4f6720468fa52498ce5729fb8c8/platform/util/src/com/intellij/util/text/ImmutableText.java

**Comment by cessen** [comment]
Thanks for the link!

Believe it or not, that is actually pretty similar to my first implementation of Ropey way back in 2015, which was based on binary AVL trees.  It is indeed a simple and effective text data structure!  However, Ropey's currently implementation, although more complex, is significantly faster.  It's also worth noting that (at least as far as I can tell from skimming the code) the IntelliJ text structure doesn't handle Unicode properly, nor does it handle lines, etc.

I definitely would like to find ways to simplify Ropey's code, but only insofar as it doesn't negatively impact performance.

**Comment by matklad** [comment]
> However, Ropey's currently implementation, although more complex, is significantly faster. 

Yeah, it totally makes sense to go with B-trees and not just AVL

> It's also worth noting that (at least as far as I can tell from skimming the code) the IntelliJ text structure doesn't handle Unicode properly, nor does it handle lines, etc.

That's actually the most interesting bit I've learned from implementation! IntelliJ itself definitely handles unicode and newline, but outside of the core text datastructure! So maybe one *shouldn't* add additional metrics to the rope? Note that I am not really an expert here, so I can't say which approach is best.

For the reference, two bits of additional infra atop of the ImmutableText are 

* [LineSet](https://github.com/JetBrains/intellij-community/blob/599ee5eba7ae56e226175eb21c4b5b5558b4177e/platform/core-impl/src/com/intellij/openapi/editor/impl/LineSet.java), for storing newlines
* [RangeMarkerTree](https://github.com/JetBrains/intellij-community/blob/5acd62037e10746ebc78e0cbc762eacc43abc46d/platform/core-impl/src/com/intellij/openapi/editor/impl/RangeMarkerTree.java) for storing highlights.

**Comment by cessen** [comment]
Ah, thanks for the additional links!  Yeah, I assumed they tracked lines externally, since... in an editor you have to track lines _somewhere_.  But I wasn't so sure about unicode, since a lot of people just kind of punt on that.

I do think there are valid engineering trade-offs to be made with respect to what you do/don't track directly in your core text data structure. But to be perfectly frank, I prefer my own choices over Intellij's.  Which I guess makes sense since I wrote Ropey, ha ha. :-)

To elaborate: I think leaving unicode scalar value and line tracking outside of your core data structure leaves some important things on the table:

1. Every text editor needs to track lines and unicode scalar values anyway, and that functionality isn't going to meaningfully vary from editor to editor, so there's not much (if any) benefit to making them modular and separate.
2. Tracking them in an external structure efficiently means that you'll be building another almost-identical tree data structure anyway, which is a cost in terms of both processing time and memory usage.

Ropey originally even tracked graphemes, but I eventually dropped that because (1) it turns out that graphemes aren't strictly defined and may, in fact, vary from editor to editor and (2) certain aspects of tracking graphemes can potentially take linear time in the length of the text, which means there are some significant engineering trade-offs to make there as well, which I didn't feel comfortable locking-into the text data structure. 

Hope that helps explain some of Ropey's choices!

**Comment by matklad** [comment]
>But I wasn't so sure about unicode, since a lot of people just kind of punt on that.

Just a coincidence, but **right now**, when inserting emoji into my presentation, I've noticed that VS Code does this wrong (and IntelliJ does it right).

>But to be perfectly frank, I prefer my own choices over Intellij's

To be clear, I don't have an opinion which is better:D

>Tracking them in an external structure efficiently means that you'll be building another almost-identical tree data structure anyway, which is a cost in terms of both processing time and memory usage.

Note that IJ's `LineSet` is a plain sorted array array, which might make sense from performance point of view, given that there are usually fare fewer newlines than other characters *in the common case*. I am not sure which piece of code handles unicode scalar values, but I *think* this is done on a per-line basis in [LineLayout](https://github.com/JetBrains/intellij-community/blob/599ee5eba7ae56e226175eb21c4b5b5558b4177e/platform/platform-impl/src/com/intellij/openapi/editor/impl/view/LineLayout.java) (which also handles bidi). This actually makes sense: if you need to do complex linear processing anyway, you might as well handle scalar values there, so as to have smaller constant factor.

Another reason why IJ might want to store offsets and newlines separately is that not all of the text in IJ needs line numbers all the time. Temporary virtual documents are used from time to time, and, as they are not shown to the user directly, they don't need line numbers (so, line set is created [lazily](https://github.com/JetBrains/intellij-community/blob/599ee5eba7ae56e226175eb21c4b5b5558b4177e/platform/platform-impl/src/com/intellij/openapi/editor/impl/view/LineLayout.java)).

**Comment by cessen** [comment]
> To be clear, I don't have an opinion which is better:D

Ha ha, fair!  And I don't actually think my choices in general are the *best* choices--this problem space is full of trade-offs.  It's just that with this *particular* choice, I'm not at all sure what IntelliJ gains.  The laziness you describe seems like a marginal benefit at best...?  But maybe I'm missing something.

> Note that IJ's LineSet is a plain sorted array array, which might make sense from performance point of view, given that there are usually fare fewer newlines than other characters in the common case.

Yeah, I noticed that too.  And I agree that doing something simple like using an array can make a lot of sense if you know that your documents are going to be under a certain size.  Honestly, for the vast majority of text files you encounter when coding, even going as far as using an array of strings (one string per line) for your core text data structure is probably perfectly reasonable, and keeps things simple.

But I suspect this means that IntelliJ will choke badly as files grow to abnormally large sizes for coding.  One of my goals with Ropey is for it to be robust in the face of anything, as long as it fits in memory.  In practice, that's probably not important for the large majority of use-cases.  But it does mean that people can build on top of Ropey without worrying about it choking.

**Comment by matklad** [comment]
Fun fact: as a result of this conversation, I've found a five-year old re-balancing bug in IntelliJ's tree :D

https://github.com/JetBrains/intellij-community/commit/b16987177e6023cd971d22a503663b7d63691bb2
