### ISSUE TITLE
Line length in columns

### ISSUE THREAD

**Issue by fominok** [cessen/ropey#29]
Hi, and thank you for the great crate!

I'm not sure that this will match goals of the project, but I came to a suggestion:
likely, this crate will be used for a text editor or something which depends on lines' length to compute
selections, sticky positions etc.; while it is possible to get line by index as a RopeSlice and get it's length, to get actual number of _columns_ developer have to take into account CRLF and if this is a last line of file or not; having a method which returns a number of columns for the line trimming `\r\n` (and other stuff you track to split on lines) from the end would be useful, at least for me.

**Comment by cessen** [comment]
Thanks for the suggestion, @fominok!

However, doing this properly is even more complicated than that.  CRLF is only one of many graphemes you would have to take into account.  For example, accented characters ([zalgo text](https://en.wikipedia.org/wiki/Combining_character#Zalgo_text) being an extreme example) need to be treated as a single character when counting columns as well.

Because of that, even if Ropey provided a way to count chars sans-line-endings, you'd still be stuck in the same position.  And because the correct solution involves solving for graphemes, I consider that out-of-scope for Ropey.

If you don't care about the more general grapheme issue, and just want a quick-and-dirty solution for ascii-only text, then I'd suggest rolling your own solution by checking the last two bytes of the line for CR, LF, and CRLF, and then subtracting from the char length of the line-slice as needed.

If you want a fully correct solution, then see the graphemes examples in Ropey's examples directory in this git repo.  You can take the line slice and run the grapheme iterator over it, counting each grapheme as you go, stopping when you hit a line ending.
