### ISSUE TITLE
What would be the proper way to process lines as &str instances?

### ISSUE THREAD

**Issue by loxs** [cessen/ropey#33]
Hi,

I am trying to read a file into a rope, parse it line by line with Nom and then, in the future, maybe write back changes.
My files are self contained lines so it makes sense to parse them line by line, so I naively do a `line.to_str()` and try to parse them, but the results surprised me, as not all lines convert properly to &str:

```
line 20: ["option \"something\"]
line 20 as_str: Some("option \"something\"\n")
line 21: ["\n"]
line 21 as_str: Some("\n")
line 22: ["option \"i", "rrelevant\"\n"]
line 22 as_str: None
```
So this is probably where the buffered reader overflows into another chunk, but what is my best option for retrieving a &str for the line, so that I can parse it?

Or should I try to run Nom directly on the RopeSlice somehow?

**Comment by cessen** [comment]
> so I naively do a line.to_str() and try to parse them

Do you mean [`as_str()`](https://docs.rs/ropey/1.2.0/ropey/struct.RopeSlice.html#method.as_str)?  There shouldn't be a `to_str()` method anywhere in Ropey.

In any case, if I understand what you're trying to do:

Unfortunately, you can't always directly get a `&str` slice of a line in Ropey.  That's because Ropey doesn't store text in contiguous memory (which isn't unique to Ropey--that's generally true of any data structure designed to efficiently edit large texts).  Because of that, some lines end up split across more than one area of memory, and can't be returned as a single `&str` slice.  This is why `as_str()` can fail, returning `None`: it will fail when the text isn't contiguous in memory.

There are a couple of ways you could handle this:

1. Do streaming parsing with nom (I think nom can do that?), where it processes text as a sequence of multiple `&str` rather than as a single contiguous `&str`.
2. Less efficiently, but more easily, you can convert each line to a [`Cow<&str>`](https://docs.rs/ropey/1.2.0/ropey/struct.RopeSlice.html#impl-From%3CRopeSlice%3C%27a%3E%3E-2) just before parsing it.  You can then borrow a `&str` slice from the `Cow<&str>` to do your parsing.  The basic idea here is that converting to `Cow<&str>` borrows when the text is contiguous in memory, and copies when it's not.  As long as your lines aren't abnormally long, the large majority should be borrows, which keeps things reasonably efficient.

The second approach would look something like this:

```rust
use std::borrow::Cow;
for line in rope.lines() {
    let cow_line = Cow::from(line);
    my_parse_function_that_takes_a_str(&cow_line);  // `&cow_line` auto-derefs to a `&str`.
}
```

Hope that helps!

**Comment by loxs** [comment]
Thanks, the second option seems to be quite good for my needs!
