### ISSUE TITLE
Performance vs other methods (Question)

### ISSUE THREAD

**Issue by sl2qf** [cessen/ropey#34]
Hi!
I noticed this cool project while developing my own text-editor. I really apologize if this is the wrong place to put it, but I have a couple of questions.

1. **How does the performance of this library compare to Xi-Rope?** I heard [here](https://www.reddit.com/r/rust/comments/accvq7/ropey_10_an_editable_text_buffer_for_rust/ed7tz7a?utm_source=share&utm_medium=web2x&context=3) that Xi-Rope was slightly faster than `ropey`, but that article was 2 years ago. By performance I mean inserting & indexing (getting a byte at position x) at random locations.
2. **How does the performance of a B-Tree rope (the design that `ropey` and `xi-rope` uses) compare to that of say a `Piece-Table`?** 
============================================
Suppose you have 20GB of data loaded into memory. I'm assuming what `ropey` and `xi-rope` do is that they break that 20GB of data into a bunch of nodes, where each node contains `BUFFER_SIZE` bytes. If you have 20GB of data & 1K node size, then you would need 20,971,520 nodes. This really bogs down random insertions & indexes.
============================================
However, a `Piece-Table` could just read all the 20GB into memory, and when you want to perform a random insertion/deletion, then it would be instant. (assuming you have made 0 edits). The downside of a `Piece-Table` is that the performance scales with how many pieces you have in the table (ie edits). If you have made 10,000 edits, then you would have to iterate through 10,000+ pieces to find out indexes. I think this can be brought down to `O(log(m))` time with a `RB-Tree`, where `m` is the number of edits made instead of the number of characters. I believe this is what `VSCode` [does](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation).

I was wondering if the chunk of text above (about the piece table) are true. If it's true, then does that mean a `Piece-Table` could be theoretically faster for general things like insertions, deletions, and indexing?

**n = number of bytes
m = number of edits**

`B-Tree Rope` Random Insertion: o(log n)
`B-Tree Rope` Random Indexing: o(log n)

`Piece-Table` Random Insertion: o(m)
`Piece-Table` Random Indexing: o(m)

`Piece-Table-With-Tree` Random Insertion: o(log m)
`Piece-Table-With-Tree` Random Indexing: o(log m)

I'm actually using `c++`, but I was curious as to how this library performs against other methods.

Thanks!

**Comment by Plisp** [comment]
These benchmarks may be of interest `https://josephg.com/ropereport/report/`. Ropey's performance is very similar, as they use similar data structures.

**Comment by sl2qf** [comment]
Thank you for the reply!



> These benchmarks may be of interest https://josephg.com/ropereport/report/. Ropey's performance is very similar, as they use similar data structures.

I think the data showed that `ropey` was third place, behind `jump_rope` and `jump_rope_c`, but it was just barely slower.
However, it was about 9x faster than `xi-rope`, which was really surprising.



> As for performance of piece tables, consider the following scenario:
> You have a 5 MB file and find/replace 100000 instances of a search pattern.
> For the piece table, this results in 200001 descriptors, assuming non-contiguous matches.
> For the rope, assuming an average fill of 900 bytes per chunk and that your replacement text is not much longer than your matches, you need around `5mil / 900 = 5500` descriptors, which is two orders of magnitude less. Clearly there's going to be a performance difference there, no matter what index structure you use.


I think I'm still going to use a `Piece-Table`, but with some type of `B-Tree`, because for my editor I think I'm going to prioritize speed scaling with file size, as normally there won't be too many edits.

> I'm curious, what kind of editor are you thinking to write?

I'm just planning to write some simple GUI `win32` (or maybe I'll put in more effort and make it cross platform) text editor. I might make it a bit more advanced later on but right now it's supposed to be really basic. It'll probably look similar to `notepad` in its early stages.

**Comment by cessen** [comment]
Ropey and xi-rope used to have about the same performance, with each performing slightly better/worse in different circumstances, but basically being on par with each other.  That's reflected in the old benchmarks that @Plisp linked to.

However, they reworked xi-rope's internals, which introduced a [significant performance regression](https://github.com/xi-editor/xi-editor/issues/771).  As of [xi-rope 0.3](https://crates.io/crates/xi-rope/0.3.0), Ropey is well over an order of magnitude faster.  And it seems like it's not considered a priority to fix.

Having said that, even with the performance regression, xi-rope is still plenty fast.  Just not as fast as Ropey.

As for piece tables, I don't have any real experience with them, but my impression is that they have both advantages and disadvantages compared to ropes.  One of the advantages is that it's easier (in theory, at least) to handle larger-than-memory files with a piece table.

**Comment by sl2qf** [comment]
Thank you for the reply!

> Ropey and xi-rope used to have about the same performance, with each performing slightly better/worse in different circumstances, but basically being on par with each other. That's reflected in the old benchmarks that @Plisp linked to.
> 
> However, they reworked xi-rope's internals, which introduced a [significant performance regression](https://github.com/xi-editor/xi-editor/issues/771). As of [xi-rope 0.3](https://crates.io/crates/xi-rope/0.3.0), Ropey is well over an order of magnitude faster. And it seems like it's not considered a priority to fix.

That's nice to know.



> As for piece tables, I don't have any real experience with them, but my impression is that they have both advantages and disadvantages compared to ropes. One of the advantages is that it's easier (in theory, at least) to handle larger-than-memory files with a piece table.

In my eyes, I think the biggest advantage (in my case) of the piece table is that the performance of it scales with the number of edits you have, not the number of characters.

However if you are planning to have many more edits, then I definitely think that the `Rope` would be a better choice.

For my case though, I think I'm gonna use a `Piece-Table` with some sort of tree structure. (Probably a type of `B-Tree`)

**Comment by cessen** [comment]
> In my eyes, I think the biggest advantage (in my case) of the piece table is that the performance of it scales with the number of edits you have, not the number of characters.
>
> However if you are planning to have many more edits, then I definitely think that the `Rope` would be a better choice.

I'm skeptical if a rope would actually be more advantageous even with many edits, assuming that the competing piece table is implemented well and uses a tree-based data structure to track the pieces.

I think the main advantage of ropes is that they're a very straightforward data structure, and allow you to fairly easily track secondary metrics like line breaks, character counts, etc. directly in the rope structure itself.  Whereas piece tables are a bit trickier to implement efficiently, and need secondary data structures to track secondary metrics.

Either way, I think both data structures are great choices for an editor.

**Comment by Plisp** [comment]
I remember a while back I implemented a piece table using a red-black tree, which turned out over an order of magnitude slower than ropey on random edits due to cache misses. Then I came to the conclusion that random access wasn't as useful as iteration, which led to a cursored linked list which was about on par with ropey in search/replace. So far it's worked quite well in my toy editor.

I've been wondering if I'm missing something here. Is random access to lines/byte offsets really something worth optimizing in a text buffer?

Most often you iterate rather than jump (in bulk, usually singular operations aren't a huge problem). I haven't seen a real use case where performance there matters, especially when `memchr` zips through newlines at multiple GB/s.

**Comment by sl2qf** [comment]
Thank you guys for all the feedback by the way!



> Either way, I think both data structures are great choices for an editor.

:D



> I've been wondering if I'm missing something here. Is random access to lines/byte offsets really something worth optimizing in a text buffer?

I think it slightly is, but only in some rare-ish scenarios. For example, if you open a large file, and you're constantly scrolling around randomly, then IMO optimizing the random access to line offsets is important. But I'm gonna do some more benchmarking.

**Comment by cessen** [comment]
> Then I came to the conclusion that random access wasn't as useful as iteration, which led to a cursored linked list which was about on par with ropey in search/replace.

Yeah, that makes sense I think.  The initial use-case I had in mind that motivated efficient random access was an editor oriented around multiple-cursor editing, along the lines of Sublime Text.  So, for example, instead of having search-and-replace, you search to select all occurrences and then start typing.  But if your cursored linked list can maintain multiple cursors into the list, I expect it would perform well in that case too.  (You could also "upgrade" it to something like a [skip list](https://en.wikipedia.org/wiki/Skip_list), and keep most of the advantages of a linked list while also gaining good random access performance, at the cost of some additional complexity.)

I certainly like replacing more complex solutions with simpler ones that work just as well.  So the idea of just replacing the whole thing with a simple linked list of text chunks is really appealing to me.  I suspect the saved complexity might just get pushed to other parts of the editor code, but that might actually be a good thing: maybe that complexity really belongs outside of the core text data structure.  I thought about that with piece tables as well: you don't have any place to track metadata about the text in the piece table data structure itself, but maybe those kinds of things are better maintained outside the core text structure anyway.

One advantage of a rope or piece table over a simple linked-list, however, is the ability to make cheap instant "clones" of the text that share memory.  Whether that's worthwhile or not probably depends on your use-case.  But, for example, it lets you do things like clone the text and send the clone to another thread for saving to disk, while the user continues to happily edit their text.  If you're always working with small texts, that's probably not a big deal.  But for really large texts it can save you from having to block the user during saving.

I really appreciate this discussion.  It's making me revisit a lot of my assumptions about what a good text editing data structure could look like.  I won't be changing Ropey (I want it to be stable for the people using it).  But the discussion is interesting nevertheless.

**Comment by Plisp** [comment]
> I'm skeptical if a rope would actually be more advantageous even with many edits, assuming that the competing piece table is implemented well and uses a tree-based data structure to track the pieces.

Are you thinking that since a rope is bounded by `log n/k = log n - log k` searches (for some chunk size k) and the piece table is bounded by `log n` (all 1-byte pieces) they should only differ by a small constant of around `log_B k` in the worst case (and usually more heavily in the piece table's favor)? That makes sense to me, especially given the extra load-balancing ropes need to manage at the leaves.

> For example, if you open a large-ish cpp file, and you write the entire file in one sitting (like 3k lines), and you're constantly scrolling around randomly, then IMO optimizing the random access to line offsets is somewhat important.

@ sl2qf I think you'll find memchr has no problem with a couple hundred KB, though the current line is probably worth caching. This feels to me like one bit of metadata that can reasonably be tracked outside the structure where it's needed.

> a simple linked list of text chunks

Admittedly I actually implemented something much uglier than a chunked list. It was a piece table backed by a doubly linked list whose nodes were pointed to by cursors. I wanted instant file loads and fast scans/edits but not absolute indexing, and so the linked list made it efficient to traverse/update the local region of the cursor. On an aesthetic level manipulating stateful cursors rather than plain indices is a downgrade imo, though there's some further potential for overloading arithmetic I didn't realize earlier. `cursor - cursor` could give you an index whilst `cursor +/- integer` could return a temporary cursor, somewhat like C pointers.

> One advantage of a rope or piece table over a simple linked-list, however, is the ability to make cheap instant "clones" of the text that share memory.

I was thinking about this a while ago and I realized you only really need multiple readers. It seems [atom](https://blog.atom.io/2017/10/12/atoms-new-buffer-implementation.html) figured this out. They mark the piece table read-only and treat it as the base immutable data block for the new "user" piece table to which edits are applied. But then if you're mutating the structure, you need to implement an operation for merging the snapshot back in and undo still needs to store all deleted text somehow. At that point I feel like a fully persistent structure would just be cleaner.

For some degree of read parallelism, I made my linked-list/cursors thread-safe and added a mechanism for invalidating outdated cursors which worked well enough for the UI thread. But it's a good point that allowing readers to fail doesn't work for background saves.

What I think would be better than existing designs is a hybrid that mutates small buffers in place, while larger chunks of text are simply pointed to and reference counted until they split up. I've been playing around with this a bit recently and I might write a paper on it once it works out. Theoretically I think it could do at least as well as a rope.

> I suspect the saved complexity might just get pushed to other parts of the editor code, but that might actually be a good thing

Aside from text buffers, I wonder what your thoughts are on the problem of mark maintenance (moving cursors on inserts, moving/invalidating on deletes). Do you track it in the text buffer (vis even stores addresses of text, which doesn't move in a piece table) or in an interval tree, or update it lazily in some manner?

> But the discussion is interesting nevertheless.

I also find the topic quite interesting :slightly_smiling_face:
