### ISSUE TITLE
B Tree-Rope design

### ISSUE THREAD

**Issue by githubuser181** [cessen/ropey#36]
I was learning about the `Rope` data structure when I saw this project.

A normal `Rope` uses a binary tree, and every node's key is the sum of its left subtree. (According to https://en.wikipedia.org/wiki/Rope_(data_structure))
The `Rope`s leaf nodes are what actually contain the string, and its key is the length of that string.

I saw in https://github.com/cessen/ropey/blob/master/design/design.md that `Ropey` uses a `B-Tree`. I also noticed that in that design paper, it shows that every single `Node`, not just the leaf nodes, contains a String.

I was kinda confused by this, and was wondering if you could explain how that works. For example, how would the searching work? (Like finding the what byte is at a specific position) In a normal `B-Tree`, to search for a key `k`, you:

Start at the root
Go through each key in the current node, and then find where `k` falls in that range of keys.
You then go to the appropriate child, and repeat.

However, I'm pretty sure that only works without duplicates.

How does `Ropey`'s design for that work? Because if the key in `Ropey`'s design is the byte count of its child, then there could be multiple duplicate byte counts.

I'm probably missing something very basic, and it would be great if you could explain this.

Also, I'm kind of curious as to why you did not use a `B+ Tree`. I feel like a `B+ Tree` is more fitting because all of the values are stored in it's leaf nodes, like a `Rope`.

Here is an image that illustrates what I mean:
![image](https://user-images.githubusercontent.com/82235749/114229103-3dd65700-992c-11eb-8527-a1abb10790c8.png)

**Comment by Plisp** [comment]
When people say btree, they typically mean a B+tree, which has better fanout and other useful properties.
This is the case with ropey, and the best source for such questions is well, the source.

But look at:
https://github.com/cessen/ropey/blob/master/src/tree/node_children.rs#L297

Searching uses the same principle as what you presented there, except generalized to multiple nodes.
You sum the cumulative sizes of each child (stored at the parent) until you get a total greater than what you're looking for. Then you just traverse into the previous child (before the total > offset you're looking for).

**Comment by githubuser181** [comment]
Ah, ok, I see how the searching works.

However, I noticed in `design.md` that the structure of the `B-Tree` (technically B+ Tree right?) is as follows:

```
enum Node {
    Internal {
        child_count: u8,
        child_byte_counts: [usize; 4],  // Max four children
        children: [Rc<Node>; 4],  // Max four children
    },
    Leaf {
        len: usize,
        [u8; 100],  // Max 100 bytes of text per leaf
    },
}
```
Where `child_byte_counts` would be the keys of the current node.

However, a `B+ Tree` requires that every node contains at **most** `k` - 1 keys, where `k` is also equal to the max number of children.

In `Ropey`'s example case, the max number of children is 4, therefore `k` would also be 4.
However, `Ropey`'s example case shows the max number of keys to also be 4, not 3.

What am I missing here?

**Comment by Plisp** [comment]
That's only a small technicality specific to ropey's [loop](https://github.com/cessen/ropey/blob/master/src/tree/node_children.rs#L297). I'm [fairly sure](https://github.com/Plisp/libpt/blob/05eb9d9760047b0ddfecbd8a9981b82c22c351df/src/btree.c#L192) that you can avoid a bounds check at each branch node though with that extra key, due to knowing your index must fall within the tree (can be checked once).

The key differentiating aspect of a b+tree is that values are only stored at the leaves, for higher fanout at branch nodes.
The actual node definition:
https://github.com/cessen/ropey/blob/master/src/tree/node.rs#L10
https://github.com/cessen/ropey/blob/master/src/tree/node_children.rs#L537
https://github.com/cessen/ropey/blob/master/src/tree/node_text.rs#L255

**Comment by cessen** [comment]
> In Ropey's example case, the max number of children is 4, therefore k would also be 4.
> However, Ropey's example case shows the max number of keys to also be 4, not 3.
>
> What am I missing here?

You're not missing anything especially important.  Indeed, the 4th key isn't necessary.  I don't recall off the top of my head why I coded it that way originally, but possibly it lets the traversal code be simpler.  And I expect any space savings would be tiny (if they would exist at all, due to alignment) in Ropey's actual implementation, since it uses a much higher branching factor than the examples in the design document.

That does make me curious, though.  If someone wants to take a crack at removing the unnecessary key and see how it affects things, I'd love to hear about it!  If it gives notable space or performance improvements then it could be worth doing--although I'm skeptical if that would be the case.
