### ISSUE TITLE
Leaf node as Gap buffer (Just Idea)

### ISSUE THREAD

**Issue by black7375** [cessen/ropey#45]
I thought of an idea while participating in an issue to make [emacs-ng multi-threaded](https://github.com/emacs-ng/emacs-ng/issues/378).

What do you think about using each leaf node as a gap buffer?
I think that simple inserts and deletes that do not cause grow operations can be faster.
(If there is a need to change the structure of the gap buffer, the existing rope is used.)

Emacs uses about 20 bytes as the size of the gap.
https://github.com/emacs-mirror/emacs/blob/55e77a811a6f137b02eb786fb00c43f0f14bb028/src/buffer.c#L571

Could it be that it consumes too many ram or causes problems with threadsafe?
An alternative to the memory problem is to keep track of the cursor position, and only use the gap buffer on the leaf node the cursor is on.

**Comment by cessen** [comment]
Hi @black7375, thanks for taking the time to write this up!

Using a gap buffer structure in the leaf nodes is certainly an interesting idea, and I think you're right that it would make repeated in-place insertions even faster.

However, it would also introduce additional complexity into a code base that (honestly) is already more complex than I would prefer.  I also suspect it wouldn't make things quite as much faster as you might think, because Ropey still needs to scan the leaf text to find where to insert, etc.  It also would very likely negatively impact the performance of non-edit operations due to fragmenting the text further (and thus e.g. hindering SIMD-based scanning, etc.).

So although I definitely find the idea interesting, and think it could work, I think I probably don't want it in Ropey.
