### ISSUE TITLE
attempt to compute `0_usize - 1_usize`, which would overflow

### ISSUE THREAD

**Issue by steewbsd** [cessen/ropey#73]
Hello, while trying to compile some cargo package (zee) which has ropey as a dependency, I ran into this error:
attempt to compute `0_usize - 1_usize`, which would overflow
![image](https://user-images.githubusercontent.com/26441684/204854069-92ccd225-74ee-4b09-9fdb-ec33f0db9d10.png)

Viewing the source, the comment above this declaration specifies this:
![image](https://user-images.githubusercontent.com/26441684/204854315-801cf850-c654-484f-ae27-c71285708f0a.png)

I am unsure whether this is an error on my side, relevant info:
rustc --version: rustc 1.65.0 (897e37553 2022-11-02)
rustup toolchain list:
stable-x86_64-unknown-linux-musl (default)
nightly-x86_64-unknown-linux-musl
Operating system: Alpine linux edge x86_64

**Comment by cessen** [comment]
This appears to be a manifestation of #56, which was fixed in Ropey 1.5.0.  It looks like you're building a version of Zee that depends on Ropey 1.4.1, which is why you're running into it.  The [latest master of Zee](https://github.com/zee-editor/zee/tree/master) uses Ropey 1.5.0, so if you download and build that instead, you should be good to go.

You could also poke the maintainer of Zee to make another crates.io release with the upgraded Ropey dependency.

**Comment by steewbsd** [comment]
Thanks, building from git solved the issue.
