### ISSUE TITLE
Rope Graphemes Example

### ISSUE THREAD

**Issue by tz629** [cessen/ropey#89]
Have you considered having [this](https://github.com/cessen/ropey/blob/387ea30b3520b7bb20c2e04c50d9e4025e81daaf/examples/graphemes_iter.rs#L18) in the crate itself? I've seen two text editors that use what you have here, and I need to use it too. It might be useful if you put this in the crate.

**Comment by cessen** [comment]
It is intentionally not part of Ropey.  There are a few reasons for that, but the main one is that Ropey is specifically designed to enable things like that to be implemented by client code.  This is both so that Ropey itself can stay leaner (and to be honest, Ropey is already bigger than I would prefer) and to give client code more control/flexibility.

Having said that, this is something that could easily be a separate crate.  I don't personally want to maintain that, but if someone else wants to publish and maintain it as an independent crate, I certainly wouldn't be opposed.  (But nor would it be endorsed as e.g. part of the Ropey project.)
